services:
  flask_restx:
    build: .
    container_name: flask_restx
    networks:
      - celery_network
    ports:
      - 5000:5000
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "app:app", "--preload"]
  redis:
    image: redis
    container_name: redis
    networks:
      - celery_network
    ports:
      - 6379:6379
  celery:
    build: .
    container_name: celery
    networks:
      - celery_network
    command: ['celery', '-A', 'task.celery_app', 'worker', '--loglevel=info']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - flask_restx
networks:
  celery_network:
    name: celery_network
    driver: bridge
